# Generated by Django 5.1.3 on 2024-11-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_is_deleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
